"""Refactor Subject to Course

Revision ID: 27a2d53c3819
Revises: ed6f7ec02efb
Create Date: 2026-06-21 16:14:09.445379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a2d53c3819'
down_revision: Union[str, None] = 'ed6f7ec02efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('credits', sa.SmallInteger(), nullable=True),
    sa.Column('color_theme', sa.String(length=7), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_code', name='uq_user_course_code')
    )
    op.create_index(op.f('ix_courses_deleted_at'), 'courses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_courses_is_archived'), 'courses', ['is_archived'], unique=False)
    op.create_index(op.f('ix_courses_semester'), 'courses', ['semester'], unique=False)
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    # Deferred drop of subjects
    op.add_column('assignments', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_assignments_subject_id'), table_name='assignments')
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.drop_constraint(op.f('assignments_subject_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('assignments', 'subject_id')
    op.add_column('classes', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('classes_subject_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('classes', 'subject_id')
    op.add_column('documents', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.create_index(op.f('ix_documents_course_id'), 'documents', ['course_id'], unique=False)
    op.drop_constraint(op.f('documents_subject_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'subject_id')
    op.add_column('learning_roadmaps', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('learning_roadmaps_subject_id_fkey'), 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'learning_roadmaps', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('learning_roadmaps', 'subject_id')
    op.add_column('quiz_results', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_quiz_results_subject_id'), table_name='quiz_results')
    op.create_index(op.f('ix_quiz_results_course_id'), 'quiz_results', ['course_id'], unique=False)
    op.drop_constraint(op.f('quiz_results_subject_id_fkey'), 'quiz_results', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_results', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quiz_results', 'subject_id')
    op.add_column('study_sessions', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('study_sessions_subject_id_fkey'), 'study_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'study_sessions', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('study_sessions', 'subject_id')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('study_sessions_subject_id_fkey'), 'study_sessions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_column('study_sessions', 'course_id')
    op.add_column('quiz_results', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_results_subject_id_fkey'), 'quiz_results', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_quiz_results_course_id'), table_name='quiz_results')
    op.create_index(op.f('ix_quiz_results_subject_id'), 'quiz_results', ['subject_id'], unique=False)
    op.drop_column('quiz_results', 'course_id')
    op.add_column('learning_roadmaps', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('learning_roadmaps_subject_id_fkey'), 'learning_roadmaps', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_column('learning_roadmaps', 'course_id')
    op.add_column('documents', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_subject_id_fkey'), 'documents', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_course_id'), table_name='documents')
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    op.drop_column('documents', 'course_id')
    op.add_column('classes', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_subject_id_fkey'), 'classes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_column('classes', 'course_id')
    op.add_column('assignments', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_subject_id_fkey'), 'assignments', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.create_index(op.f('ix_assignments_subject_id'), 'assignments', ['subject_id'], unique=False)
    op.drop_column('assignments', 'course_id')
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('teacher', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subjects_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey'))
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_semester'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_archived'), table_name='courses')
    op.drop_index(op.f('ix_courses_deleted_at'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
