"""Add documents and chunks

Revision ID: 39f706ee130f
Revises: 6b0a906750a0
Create Date: 2026-06-21 16:38:03.628263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f706ee130f'
down_revision: Union[str, None] = '6b0a906750a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.Text(), nullable=False))
    postgresql.ENUM('processing', 'ready', 'failed', name='documentstatus').create(op.get_bind())
    op.add_column('documents', sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='documentstatus'), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=postgresql.ENUM('pdf', 'txt', 'docx', name='filetype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_column('documents', 'processed')
    op.drop_column('documents', 's3_key')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'qdrant_collection')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('qdrant_collection', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('s3_key', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pdf', 'txt', 'docx', name='filetype'),
               existing_nullable=False)
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'title')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
