"""Add ScheduleEvents

Revision ID: 8a224f930bd6
Revises: 27a2d53c3819
Create Date: 2026-06-21 16:22:42.806906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a224f930bd6'
down_revision: Union[str, None] = '27a2d53c3819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('CLASS', 'LAB', 'TUTORIAL', 'EXAM', 'ASSIGNMENT', 'STUDY_SESSION', 'REVISION', 'PERSONAL', name='eventtype'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('color_theme', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_events_course_id'), 'schedule_events', ['course_id'], unique=False)
    op.create_index(op.f('ix_schedule_events_deleted_at'), 'schedule_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_schedule_events_event_type'), 'schedule_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_schedule_events_start_time'), 'schedule_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_schedule_events_user_id'), 'schedule_events', ['user_id'], unique=False)
    op.drop_index(op.f('ix_classes_user_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', postgresql.ARRAY(sa.SMALLINT()), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('room', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('classes_course_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('classes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('classes_pkey'))
    )
    op.create_index(op.f('ix_classes_user_id'), 'classes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_schedule_events_user_id'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_start_time'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_event_type'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_deleted_at'), table_name='schedule_events')
    op.drop_index(op.f('ix_schedule_events_course_id'), table_name='schedule_events')
    op.drop_table('schedule_events')
    # ### end Alembic commands ###
