"""Add unit 9 roadmap engine

Revision ID: c19cdcbd5e1a
Revises: abad2e176244
Create Date: 2026-06-21 16:59:23.219356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19cdcbd5e1a'
down_revision: Union[str, None] = 'abad2e176244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.SmallInteger(), nullable=True),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='nodedifficulty'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='nodepriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='nodestatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('mastery_target', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['learning_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_nodes_parent_id'), 'roadmap_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_roadmap_id'), 'roadmap_nodes', ['roadmap_id'], unique=False)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_node_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('completion_percentage', sa.SmallInteger(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_progress_roadmap_node_id'), 'roadmap_progress', ['roadmap_node_id'], unique=True)
    op.create_index(op.f('ix_roadmap_progress_user_id'), 'roadmap_progress', ['user_id'], unique=False)
    op.add_column('learning_roadmaps', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('learning_roadmaps', sa.Column('goal', sa.Text(), nullable=False))
    op.add_column('learning_roadmaps', sa.Column('target_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('learning_roadmaps', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_learning_roadmaps_course_id'), 'learning_roadmaps', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_roadmaps_deleted_at'), 'learning_roadmaps', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('learning_roadmaps_course_id_fkey'), 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'learning_roadmaps', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learning_roadmaps', 'topic')
    op.drop_column('learning_roadmaps', 'phases')
    op.drop_column('learning_roadmaps', 'generated_by')
    op.drop_column('learning_roadmaps', 'learning_goal')
    op.drop_column('learning_roadmaps', 'current_phase')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_roadmaps', sa.Column('current_phase', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('learning_roadmaps', sa.Column('learning_goal', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('learning_roadmaps', sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('learning_roadmaps', sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('learning_roadmaps', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('learning_roadmaps_course_id_fkey'), 'learning_roadmaps', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_learning_roadmaps_deleted_at'), table_name='learning_roadmaps')
    op.drop_index(op.f('ix_learning_roadmaps_course_id'), table_name='learning_roadmaps')
    op.drop_column('learning_roadmaps', 'deleted_at')
    op.drop_column('learning_roadmaps', 'target_date')
    op.drop_column('learning_roadmaps', 'goal')
    op.drop_column('learning_roadmaps', 'title')
    op.drop_index(op.f('ix_roadmap_progress_user_id'), table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_roadmap_node_id'), table_name='roadmap_progress')
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('ix_roadmap_nodes_roadmap_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_parent_id'), table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    # ### end Alembic commands ###
